In [ ]:
# ╔══════════════════════════════════════════════════════════╗
# ║                    DATA CLEANING                         ║
# ╚══════════════════════════════════════════════════════════╝

In [2]:
# ── Imports Libraries ───────────────────────────────────────
import pandas as pd
import numpy as np
import seaborn as sns

sns.set_theme(style="whitegrid")
pd.set_option("display.float_format", "{:,.2f}".format)

In [4]:
df = pd.read_csv("../dataset/raw/HouseListings-Top45Cities.csv", encoding="latin-1")
df.to_csv("../dataset/raw/HouseListings-Top45Cities.csv", index=False, encoding="utf-8")

print("✅ File converted and saved as UTF-8")

✅ File converted and saved as UTF-8

In [119]:
# ── Load Raw Data ─────────────────────────────────
df = pd.read_csv("../dataset/raw/HouseListings-Top45Cities.csv")
df.head(10)

,City,Price,Address,Number_Beds,Number_Baths,Province,Population,Latitude,Longitude,Median_Family_Income
0,Toronto,"779,900.00",#318 -20 SOUTHPORT ST,3,2,Ontario,5647656,43.74,-79.37,"97,000.00"
1,Toronto,"799,999.00",#818 -60 SOUTHPORT ST,3,1,Ontario,5647656,43.74,-79.37,"97,000.00"
2,Toronto,"799,900.00",#714 -859 THE QUEENSWAY,2,2,Ontario,5647656,43.74,-79.37,"97,000.00"
3,Toronto,"1,200,000.00",275 MORTIMER AVE,4,2,Ontario,5647656,43.74,-79.37,"97,000.00"
4,Toronto,"668,800.00",#420 -388 RICHMOND ST,1,1,Ontario,5647656,43.74,-79.37,"97,000.00"
5,Toronto,"548,000.00",#2503 -99 HARBOUR SQ,0,1,Ontario,5647656,43.74,-79.37,"97,000.00"
6,Toronto,"669,900.00",#817 -151 DAN LECKIE WAY,2,1,Ontario,5647656,43.74,-79.37,"97,000.00"
7,Toronto,"699,000.00",#1107 -438 KING ST W,2,2,Ontario,5647656,43.74,-79.37,"97,000.00"
8,Toronto,"978,000.00",#2708 -20 EDWARD ST,3,2,Ontario,5647656,43.74,-79.37,"97,000.00"
9,Toronto,"958,000.00",#4616 -386 YONGE ST,2,2,Ontario,5647656,43.74,-79.37,"97,000.00"

In [120]:
print("Shape:", df.shape)

Shape: (35768, 10)

In [121]:
# ── Basic Info ────────────────────────────────────
print("── Data Types ──")
df.dtypes

── Data Types ──

City                     object
Price                   float64
Address                  object
Number_Beds               int64
Number_Baths              int64
Province                 object
Population                int64
Latitude                float64
Longitude               float64
Median_Family_Income    float64
dtype: object

In [122]:
print("── Missing Values ──")
df.isnull().sum()

── Missing Values ──

City                    0
Price                   0
Address                 0
Number_Beds             0
Number_Baths            0
Province                0
Population              0
Latitude                0
Longitude               0
Median_Family_Income    0
dtype: int64

In [123]:
print("── Basic Stats ──")
df.describe()

── Basic Stats ──

,Price,Number_Beds,Number_Baths,Population,Latitude,Longitude,Median_Family_Income
count,"35,768.00","35,768.00","35,768.00","35,768.00","35,768.00","35,768.00","35,768.00"
mean,"943,296.25",3.28,2.53,"636,015.09",47.45,-98.42,"89,643.10"
std,"1,020,110.37",1.73,1.37,"1,120,015.63",3.33,22.28,"12,132.35"
min,"21,500.00",0.00,0.00,"63,382.00",42.28,-123.94,"62,400.00"
25%,"459,900.00",2.00,2.00,"109,167.00",43.87,-122.32,"82,000.00"
50%,"699,000.00",3.00,2.00,"242,460.00",49.02,-104.61,"89,000.00"
75%,"1,095,000.00",4.00,3.00,"522,888.00",49.89,-79.87,"97,000.00"
max,"37,000,000.00",109.00,59.00,"5,647,656.00",53.92,63.10,"133,000.00"

In [124]:
# ── checking empty data and filling ─────────────────────
print("── Number_Beds ──")
Number_Beds = df[(df["Number_Beds"] == 0)]
Number_Beds.shape

── Number_Beds ──

(769, 10)

In [125]:
print("── Number_Baths ──")
Number_Baths = df[(df["Number_Baths"] == 0)]
Number_Baths.shape

── Number_Baths ──

(658, 10)

In [126]:
print("── Both Number_Beds and Number_Baths ──")
Both_Beds_Baths = df[((df["Number_Beds"] == 0) & (df["Number_Baths"] == 0))]
Both_Beds_Baths.shape

── Both Number_Beds and Number_Baths ──

(601, 10)

In [127]:
df.shape

(35768, 10)

In [128]:
# Replace 0 with NaN first
df["Number_Beds"]  = df["Number_Beds"].replace(0, np.nan)
df["Number_Baths"] = df["Number_Baths"].replace(0, np.nan)

In [129]:
# Fill using median per city
df["Number_Beds"]  = df.groupby("City")["Number_Beds"].transform(
    lambda x: x.fillna(x.median())
)
df["Number_Baths"] = df.groupby("City")["Number_Baths"].transform(
    lambda x: x.fillna(x.median())
)

In [130]:
df.drop(columns=["Address"], inplace=True)

In [131]:
# ── Remove Duplicates ─────────────────────────────
print(df.duplicated().sum())

8579

In [132]:
df[df.duplicated()].head()

,City,Price,Number_Beds,Number_Baths,Province,Population,Latitude,Longitude,Median_Family_Income
32,Toronto,"499,900.00",2.00,1.00,Ontario,5647656,43.74,-79.37,"97,000.00"
65,Toronto,"998,000.00",4.00,2.00,Ontario,5647656,43.74,-79.37,"97,000.00"
69,Toronto,"799,900.00",2.00,2.00,Ontario,5647656,43.74,-79.37,"97,000.00"
77,Toronto,"699,000.00",2.00,1.00,Ontario,5647656,43.74,-79.37,"97,000.00"
80,Toronto,"699,000.00",2.00,1.00,Ontario,5647656,43.74,-79.37,"97,000.00"

In [133]:
before = len(df)
df.drop_duplicates(inplace=True)
print(f"Dropped {before - len(df)} duplicates. Remaining: {len(df)}")

Dropped 8579 duplicates. Remaining: 27189

In [134]:
# ── Strip Whitespace from Strings ────────────────
df.apply(lambda col: col.astype(str).str.contains(r'^\s|\s$', regex=True).sum())

City                    0
Price                   0
Number_Beds             0
Number_Baths            0
Province                0
Population              0
Latitude                0
Longitude               0
Median_Family_Income    0
dtype: int64

In [135]:
# ── Validate Lat / Lon ────────────────────────────
print("\nLatitude  — min:", df["Latitude"].min(),  "max:", df["Latitude"].max())
print("Longitude — min:", df["Longitude"].min(), "max:", df["Longitude"].max())
print("Missing coords:", df[["Latitude","Longitude"]].isnull().sum().sum())

Latitude  — min: 42.2833 max: 53.9169
Longitude — min: -123.9364 max: 63.1005
Missing coords: 0

In [136]:
# Save cleaned dataset
df.to_csv("../dataset/cleaned/housing_cleaned.csv", index=False)
print("\n✅ Saved → data/processed/housing_cleaned.csv")

✅ Saved → data/processed/housing_cleaned.csv